---
name: Fey-Loader
version: 0.01
author:
  - 'Dave Rolsky, <autarch@urth.org>'
abstract: Load your schema defintion from a DBMS
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Fey: 0
  Moose: 0
  Scalar::Util: 0
build_requires:
  Test::More: 0
provides:
  Fey::Loader:
    file: lib/Fey/Loader.pm
    version: 0.01
  Fey::Loader::DBI:
    file: lib/Fey/Loader/DBI.pm
  Fey::Loader::Pg:
    file: lib/Fey/Loader/Pg.pm
  Fey::Loader::SQLite:
    file: lib/Fey/Loader/SQLite.pm
  Fey::Loader::mysql:
    file: lib/Fey/Loader/mysql.pm
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
